export const siteConfig = {
  name: 'Sathyanantham V',
  title: 'Sathyanantham V — Lead Software Engineer & AI Architect',
  description:
    'Senior AI/Full-Stack Engineer with 13+ years building scalable systems. Specializing in AI-enabled applications, cloud architecture, and team leadership.',
  url: 'https://sathyanantham.ai',
  ogImage: '/images/og-default.png',
  links: {
    github: 'https://github.com/sathyanantham',
    linkedin: 'https://linkedin.com/in/sathyanantham',
    twitter: 'https://twitter.com/sathyanantham',
    email: 'mailto:sathyanantham.v@gmail.com',
  },
  author: {
    name: 'Sathyanantham V',
    role: 'Lead Software Engineer & AI Architect',
    experience: '13+ years',
    location: 'Chennai, India',
    bio: 'Building AI-enabled systems that scale. Former Lead Engineer at Nextuple. Passionate about clean architecture, developer experience, and the intersection of AI and software engineering.',
  },
  navigation: [
    { name: 'Home', href: '/' },
    { name: 'Projects', href: '/projects' },
    { name: 'Blog', href: '/blog' },
    { name: 'Experience', href: '/#experience' },
    { name: 'Contact', href: '/#contact' },
  ],
  stats: [
    { label: 'Years Experience', value: '13+' },
    { label: 'Projects Delivered', value: '50+' },
    { label: 'Team Members Led', value: '20+' },
    { label: 'Technologies', value: '30+' },
  ],
  skills: {
    frontend: [
      'React',
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Framer Motion',
      'Redux',
      'GraphQL',
    ],
    backend: [
      'Node.js',
      'Python',
      'FastAPI',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'GraphQL',
      'REST APIs',
    ],
    cloud: ['AWS', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    ai: [
      'LangChain',
      'LangGraph',
      'OpenAI',
      'Anthropic',
      'Vector DBs',
      'RAG',
      'Fine-tuning',
      'Agents',
    ],
    leadership: [
      'Team Lead',
      'Architecture',
      'Mentoring',
      'Code Review',
      'Agile/Scrum',
      'System Design',
    ],
  },
};

export const metadata = {
  title: {
    default: siteConfig.title,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    'AI Engineer',
    'Full Stack Developer',
    'Lead Software Engineer',
    'Software Architect',
    'Machine Learning',
    'LLM',
    'RAG',
    'LangChain',
    'Next.js',
    'React',
    'TypeScript',
    'Python',
    'AWS',
    'Kubernetes',
  ],
  authors: [{ name: siteConfig.author.name }],
  creator: siteConfig.author.name,
  publisher: siteConfig.author.name,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.url,
    title: siteConfig.title,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.title,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: '@sathyanantham',
  },
  verification: {
    google: 'google-site-verification-code',
  },
};

export const themeConfig = {
  colors: {
    light: {
      background: '0 0% 100%',
      foreground: '222 47% 4%',
      card: '0 0% 100%',
      'card-foreground': '222 47% 4%',
      border: '214 32% 91%',
      ring: '188 94% 43%',
      primary: '188 94% 43%',
      'primary-foreground': '222 47% 4%',
      secondary: '210 40% 96%',
      'secondary-foreground': '222 47% 4%',
      muted: '210 40% 96%',
      'muted-foreground': '215 16% 47%',
      accent: '188 94% 43%',
      'accent-foreground': '222 47% 4%',
      destructive: '0 84% 60%',
      'destructive-foreground': '0 0% 98%',
    },
    dark: {
      background: '222 47% 4%',
      foreground: '210 40% 98%',
      card: '222 47% 7%',
      'card-foreground': '210 40% 98%',
      border: '217 33% 17%',
      ring: '188 94% 43%',
      primary: '188 94% 43%',
      'primary-foreground': '222 47% 4%',
      secondary: '217 33% 17%',
      'secondary-foreground': '210 40% 98%',
      muted: '217 33% 17%',
      'muted-foreground': '215 20% 65%',
      accent: '188 94% 43%',
      'accent-foreground': '222 47% 4%',
      destructive: '0 62% 30%',
      'destructive-foreground': '0 0% 98%',
    },
  },
  radius: '0.75rem',
  fonts: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
    mono: 'var(--font-mono)',
  },
};

export const animationConfig = {
  durations: {
    fast: 150,
    normal: 300,
    slow: 500,
    slower: 700,
  },
  easings: {
    easeOut: [0.16, 1, 0.3, 1],
    easeIn: [0.7, 0, 0.84, 0],
    easeInOut: [0.87, 0, 0.13, 1],
    spring: { stiffness: 300, damping: 30 },
    springGentle: { stiffness: 100, damping: 20 },
  },
  stagger: 0.1,
};